yarnPath: .yarn/releases/yarn-4.1.1.cjs

nodeLinker: node-modules

npmScopes:
  mis:
    npmAlwaysAuth: true
    npmPublishRegistry: 'http://nexus.bars.group/repository/medmis-npm/'
    npmRegistryServer: 'http://nexus.bars.group/repository/medmis-npm/'
  plex:
    npmRegistryServer: 'http://nexus.bars.group/repository/barsup-net-npm/'
    npmAuthToken: 'NpmToken.f4c9fdd3-9c4a-38a8-9ef4-59f63dc8bfb9'

unsafeHttpWhitelist:
  - nexus.bars.group
changesetBaseRefs:
  - "develop"
  - "origin/develop"
